version: '3.8'

services:
  census:
    build: ./Votum/
    tty: true
    command: nodemon --legacy-watch server.js
    ports:
      - 3000:3000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres-db
    volumes:
      - ./Votum:/app
      - /app/node_modules
  postgres-db:
    image: postgres:12.7-buster
    volumes:
      - postgres-dev:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - 5432:5432

volumes:
  postgres-dev:
