version: '3.3'

services:
    votum:
        build: ./Votum/
        tty: true
        command: python3 app.py
        ports:
            - 5000:5000
        env_file:
            - ./.env.dev
        depends_on:
            - postgres-db
        volumes:
            - type: bind
              source: ./Votum/Project
              target: /app/
    postgres-db:
        image: postgres:latest
        volumes:
            - postgres-dev:/var/lib/postgresql/data/
        env_file:
            - ./.env.dev
        ports:
            - 5432:5432

volumes:
    postgres-dev: