version: '3.3'

services:
  votum:
    build: ./votum/
    tty: true
    command: python3 app.py
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres-db
    volumes:
      - type: bind
        source: ./votum/app
        target: /app/
  postgres-db:
    image: postgres:12.7-buster
    volumes:
      - postgres-dev:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - 5432:5432

volumes:
  postgres-dev:
