version: '3.8'

services:
  census:
    build: ./Votum/
    tty: true
    command: nodemon --legacy-watch server.js
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres-db
    volumes:
      - ./Votum:/app
      - /app/node_modules
  postgres-db:
    image: postgres:12.7-buster
    volumes:
      - postgres-dev:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432
  redis:
    image: 'redis:alpine'
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    env_file:
      - ./.env
    command: >
      --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    volumes:
      - redis:/data

volumes:
  postgres-dev:
  redis:
